spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  sql.init.mode: always

---
spring:
  config:
    activate:
      on-profile: testdb
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always



